### ISSUE TITLE
Migrate from plugin to module

### ISSUE THREAD

**Issue by benmccann** [edulify/play-geolocation-module.edulify.com#9]
See https://www.playframework.com/documentation/2.4.x/PluginsToModules

**Comment by sovaalexandr** [comment]
Already done since Play-2.4 released. Have you seen [Play-2.4 version](https://github.com/edulify/play-geolocation-module.edulify.com/tree/play-2.4.0)?

**Comment by marcospereira** [comment]
@benmccann version 2.0.0 of the **module** was fully migrated to support Play 2.4.x. :-)

**Comment by marcospereira** [comment]
BTW, the new release was possible only because of the work done by @sovaalexandr.

Thank you.

**Comment by benmccann** [comment]
The README still talks about the old version. Is there a reason you don't link to the new version from the main page?

**Comment by marcospereira** [comment]
@benmccann I'm not seeing the old version anymore, at least not at the master branch. Which part of the readme is looking old to you?

https://github.com/edulify/play-geolocation-module.edulify.com/blob/master/README.md

**Comment by marcospereira** [comment]
It could be that I've enthusiastically close the issue before tagging/pushing the new version. :-)

**Comment by benmccann** [comment]
Ok, cool. Looks updated now. Maybe I looked before your most recent changes
